DogBreedApp/DogBreedApp/Controllers/QuizController.cs
using AutoMapper;
using DogBreedApp.Data;
using DogBreedApp.Data.Entities;
using DogBreedApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DogBreedApp.Controllers
{
    [Authorize]
    public class QuizController : Controller
    {
        private readonly ILogger<QuizController> logger;
        private readonly IQuizRepository repository;
        private readonly IMapper mapper;
        private readonly UserManager<User> userManager;

        public QuizController(ILogger<QuizController> logger, IQuizRepository repository, IMapper mapper, UserManager<User> userManager)
        {
            this.logger = logger;
            this.repository = repository;
            this.mapper = mapper;
            this.userManager = userManager;
        }

        public IActionResult GetQuiz()
        {
            return View(GetQuestionViewModels());
        }

        [HttpPost]
        public async Task<IActionResult> GetQuiz(IFormCollection results)
        {
            try
            {
                if (results.Count == 18)
                {
                    List<int> answerIds = new List<int>();
                    for (int i = 0; i < results.Count; i++)
                    {
                        if (results.ElementAt(i).Key.Contains("question_"))
                        {
                            string value = results.ElementAt(i).Value;
                            int answerId = Int32.Parse(value);
                            answerIds.Add(answerId);
                        }
                    }
                    string username = this.User.Identity.Name;
                    var currentUser = await userManager.FindByNameAsync(username);

                    if (!AddUserAnswers(currentUser, answerIds))
                    {
                        throw new Exception("Failed to save answers!");
                    }

                    return RedirectToAction("Matches", "Recommendation");
                }
                else
                {
                    ModelState.AddModelError("", "Please answer all the questions!");
                }
            }
            catch (Exception ex)
            {
                logger.LogError($"Failed to save the answers: {ex}");
                ModelState.AddModelError("", "Failed to save answers!");
            }
            return View(GetQuestionViewModels());
        }

        private bool AddUserAnswers(User currentUser, List<int> answerIds)
        {
            ICollection<UserAnswer> currentUserAnswers = repository.GetUserAnswers(currentUser);

            if (currentUserAnswers.Count != 0)
            {
                foreach(UserAnswer currentUserAnswer in currentUserAnswers)
                {
                    repository.DeleteUserAnswer(currentUserAnswer);
                }  
            }

            foreach (int answerId in answerIds)
            {
                Answer answer = repository.GetAnswer(answerId);
                UserAnswer userAnswer = new UserAnswer()
                {
                    Answer = answer,
                    User = currentUser
                };
                repository.AddUserAnswer(userAnswer);
            }

            if (repository.SaveAll())
            {
                return true;
            }

            return false;
        }

        private IEnumerable<QuestionViewModel> GetQuestionViewModels()
        {
            var questions = repository.GetQuestions(true);
            return mapper.Map<IEnumerable<Question>, IEnumerable<QuestionViewModel>>(questions);
        }
    }
}

DogBreedApp/DogBreedApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DogBreedApp</title>
    @*<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />*@

    <environment include="Development">
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
        <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
        <link href="~/css/circle.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"><i class="fa fa-paw"></i> DogBreedApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="AllDogBreeds">All Dog Breeds</a></li>
                    <li><a asp-area="" asp-controller="Quiz" asp-action="GetQuiz">Take Quiz</a></li>
                    <li><a asp-area="" asp-controller="Recommendation" asp-action="Matches">My Matches</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                    }
                </ul>
            </div>
        </div>
    </nav>
    <div class="">
        @RenderBody()
        <hr />
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>